try docker push with ecr

diff --git a/.github/workflows/hello-ubuntu-container.yml b/.github/workflows/hello-ubuntu-container.yml
--- a/.github/workflows/hello-ubuntu-container.yml
+++ b/.github/workflows/hello-ubuntu-container.yml
@@ -25,12 +25,20 @@ jobs:
         # run: |
           # echo Logging in to Amazon ECR...
           # aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com
-      - name: docker_build
+      - name: Build, tag, and push docker image to Amazon ECR
+        env:
+          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          REPOSITORY: helloworld
+          IMAGE_TAG: ${{ github.sha }}
         run: |
-          echo "docker info..." && docker info || echo "docker info failed!!!"
-          docker build -t helloworld:latest ./helloworld || echo "docker build failed!!!"
-          docker tag helloworld:latest $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/helloworld:latest || echo "docker tag failed!!!"
-          docker push $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/helloworld:latest || echo "docker push failed!!!"
+          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./helloworld
+          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
+      # - name: docker_build
+      #   run: |
+      #     echo "docker info..." && docker info || echo "docker info failed!!!"
+      #     docker build -t helloworld:latest ./helloworld || echo "docker build failed!!!"
+      #     docker tag helloworld:latest $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/helloworld:latest || echo "docker tag failed!!!"
+      #     docker push $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/helloworld:latest || echo "docker push failed!!!"
       - name: docker_run
         run: |
           echo "docker info..." && docker info || echo "docker info failed!!!"
